### ISSUE TITLE
Key storage

### ISSUE THREAD

**Issue by holdank** [thehemi/Dibbr#2]
i haven't gotten deep into the code here, but noticed tokens being stored in memory.  are these encrypted?

https://github.com/thehemi/Dibbr/blob/7925aa4cda367700cbd314221224ccc8ca953846/Program.cs#L110

**Comment by holdank** [comment]
also, idk if there's even anything malicious someone could do with your openai key, but if so, since you can't outrun your git history - you may want to do this.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by thehemi** [comment]
The OpenAI keys got invalidated immediately. The keys are stored in dibbr.dll.config, a file which is generated at runtime based on what you enter, then saved to disk. On disk they are not encrypted, that would not achieve anything useful that I can think of.
